package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// GenerateContextFiles creates AGENTS.md and CLAUDE.md with live stats from the index
func GenerateContextFiles(repoPath string, store StoreInterface) error {
	stats, err := store.Stats()
	if err != nil {
		return fmt.Errorf("get stats: %w", err)
	}

	clusters, err := store.AllClusters()
	if err != nil {
		return fmt.Errorf("get clusters: %w", err)
	}

	processes, err := store.AllProcesses()
	if err != nil {
		return fmt.Errorf("get processes: %w", err)
	}

	agentsMD := generateAgentsMDTemplate(stats, clusters, processes, repoPath)

	if err := os.WriteFile(filepath.Join(repoPath, "AGENTS.md"), []byte(agentsMD), 0644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	if err := os.WriteFile(filepath.Join(repoPath, "CLAUDE.md"), []byte(agentsMD), 0644); err != nil {
		return fmt.Errorf("write CLAUDE.md: %w", err)
	}

	return nil
}

// StoreInterface abstracts the store for dependency injection
type StoreInterface interface {
	Stats() (Stats, error)
	AllClusters() ([]Community, error)
	AllProcesses() ([]Process, error)
}

// Stats holds index statistics
type Stats struct {
	Nodes     int
	Edges     int
	Clusters  int
	Processes int
}

// Process represents an execution flow
type Process struct {
	ID   string
	Name string
}

func clusterList(clusters []Community) string {
	if len(clusters) == 0 {
		return "No clusters detected."
	}
	var result string
	for _, c := range clusters {
		result += fmt.Sprintf("- **%s**: %d files (cohesion: %.2f)\n", c.Label, len(c.Members), c.CohesionScore)
	}
	return result
}

func processList(processes []Process) string {
	if len(processes) == 0 {
		return "No execution flows traced."
	}
	var result string
	for _, p := range processes {
		result += fmt.Sprintf("- %s\n", p.Name)
	}
	return result
}

// generateAgentsMDTemplate generates the AGENTS.md content with MCP setup instructions
func generateAgentsMDTemplate(stats Stats, clusters []Community, processes []Process, repoPath string) string {
	var sb strings.Builder

	sb.WriteString("# Mimir Index — Agent Context\n\n")
	sb.WriteString("> Auto-generated by mimir analyze. Do not edit manually.\n\n")

	// Repository stats
	sb.WriteString(fmt.Sprintf(`## Repository stats
- Symbols indexed: %d
- Edges (relationships): %d
- Functional clusters: %d
- Execution flows traced: %d
- Last indexed: %s

`, stats.Nodes, stats.Edges, stats.Clusters, stats.Processes, time.Now().Format("2006-01-02 15:04")))

	// MCP Setup section
	sb.WriteString(`## MCP Setup (Required for all editors)

Mimir exposes its code intelligence via MCP (Model Context Protocol). **CLI commands like ` + "`mimir query`" + ` won't work directly** — you must use MCP tools through a running daemon.

### Step 1: Start the MCP daemon

**Recommended** (persistent background service):
` + "```bash\n" + `
mimir daemon start
` + "```" + `

**Alternative** (stdio mode, one-off sessions):
` + "```bash\n" + `
mimir mcp
` + "```" + `

### Step 2: Configure your editor

Mimir auto-configures MCP servers for these editors:

| Editor | Config File | MCP Key |
|--------|-------------|---------|
| Claude Code | ` + "`~/.claude/mcp.json`" + ` | ` + "`mcpServers`" + ` |
| GitHub Copilot (VS Code) | ` + "`settings.json`" + ` | ` + "`github.copilot.mcpServers`" + ` |
| Cursor | ` + "`mcp.json`" + ` | ` + "`mcpServers`" + ` |
| Windsurf | ` + "`mcp.json`" + ` | ` + "`mcpServers`" + ` |
| OpenCode | ` + "`~/.config/opencode/config.json`" + ` | ` + "`mcp`" + ` |
| Zed | ` + "`settings.json`" + ` | ` + "`context_servers`" + ` |

After running ` + "`mimir analyze`" + `, restart your editor to pick up the MCP server configuration.

### Step 3: Use MCP tools

Once the daemon is running, agents can call:
- ` + "`query()`" + ` — hybrid semantic + BM25 search
- ` + "`context(symbol)`" + ` — 360-degree view with call chains
- ` + "`impact(symbol, direction)`" + ` — blast radius before editing
- ` + "`detect_changes()`" + ` — pre-commit risk analysis
- ` + "`rename(old, new)`" + ` — safe coordinated rename across all files
- ` + "`cypher(query)`" + ` — custom graph queries

`)

	// Functional clusters
	sb.WriteString("## Functional clusters (modules)\n")
	sb.WriteString(clusterList(clusters))
	sb.WriteString("\n")

	// Execution flows
	sb.WriteString("## Execution flows\n")
	sb.WriteString(processList(processes))
	sb.WriteString("\n")

	// Usage for agents
	sb.WriteString(fmt.Sprintf(`## Usage for agents
Always run impact() before editing any shared utility.
Use query() instead of grep when searching for functionality.
Read mimir://repo/%s/context before starting any task.
`, filepath.Base(repoPath)))

	return sb.String()
}
