package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// GenerateContextFiles creates AGENTS.md and CLAUDE.md with live stats from the index
func GenerateContextFiles(repoPath string, store StoreInterface) error {
	stats, err := store.Stats()
	if err != nil {
		return fmt.Errorf("get stats: %w", err)
	}

	clusters, err := store.AllClusters()
	if err != nil {
		return fmt.Errorf("get clusters: %w", err)
	}

	processes, err := store.AllProcesses()
	if err != nil {
		return fmt.Errorf("get processes: %w", err)
	}

	agentsMD := fmt.Sprintf(`# Mimir Index — Agent Context

> Auto-generated by mimir analyze. Do not edit manually.

## Repository stats
- Symbols indexed: %d
- Edges (relationships): %d
- Functional clusters: %d
- Execution flows traced: %d
- Last indexed: %s

## MCP server
This repo is indexed. Connect via MCP to get full graph intelligence:
- mimir query — hybrid semantic + BM25 search
- mimir context <symbol> — 360-degree view with call chains
- mimir impact <symbol> — blast radius before editing
- mimir detect_changes — pre-commit risk analysis
- mimir rename — safe coordinated rename across all files

## Functional clusters (modules)
%s

## Execution flows
%s

## Usage for agents
Always run impact() before editing any shared utility.
Use query() instead of grep when searching for functionality.
Read mimir://repo/%s/context before starting any task.
`, stats.Nodes, stats.Edges, stats.Clusters, stats.Processes,
		time.Now().Format("2006-01-02 15:04"),
		clusterList(clusters), processList(processes),
		filepath.Base(repoPath))

	if err := os.WriteFile(filepath.Join(repoPath, "AGENTS.md"), []byte(agentsMD), 0644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	if err := os.WriteFile(filepath.Join(repoPath, "CLAUDE.md"), []byte(agentsMD), 0644); err != nil {
		return fmt.Errorf("write CLAUDE.md: %w", err)
	}

	return nil
}

// StoreInterface abstracts the store for dependency injection
type StoreInterface interface {
	Stats() (Stats, error)
	AllClusters() ([]Community, error)
	AllProcesses() ([]Process, error)
}

// Stats holds index statistics
type Stats struct {
	Nodes     int
	Edges     int
	Clusters  int
	Processes int
}

// Process represents an execution flow
type Process struct {
	ID   string
	Name string
}

func clusterList(clusters []Community) string {
	if len(clusters) == 0 {
		return "No clusters detected."
	}
	var result string
	for _, c := range clusters {
		result += fmt.Sprintf("- **%s**: %d files (cohesion: %.2f)\n", c.Label, len(c.Members), c.CohesionScore)
	}
	return result
}

func processList(processes []Process) string {
	if len(processes) == 0 {
		return "No execution flows traced."
	}
	var result string
	for _, p := range processes {
		result += fmt.Sprintf("- %s\n", p.Name)
	}
	return result
}
